//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayscaleCalc.Payscale {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.payscale.com/compensationSearch/060930", ConfigurationName="Payscale.PayScaleQuoteServiceSoap")]
    public interface PayScaleQuoteServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.payscale.com/compensationSearch/060930/SuggestJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CompensationSearchResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CompensationSearchRequest))]
        PayscaleCalc.Payscale.SuggestJobsResponse SuggestJobs(PayscaleCalc.Payscale.SuggestJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.payscale.com/compensationSearch/060930/SuggestJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<PayscaleCalc.Payscale.SuggestJobsResponse> SuggestJobsAsync(PayscaleCalc.Payscale.SuggestJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.payscale.com/compensationSearch/060930/PayScaleQuote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CompensationSearchResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CompensationSearchRequest))]
        PayscaleCalc.Payscale.PayScaleQuoteResponse PayScaleQuote(PayscaleCalc.Payscale.PayScaleQuoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.payscale.com/compensationSearch/060930/PayScaleQuote", ReplyAction="*")]
        System.Threading.Tasks.Task<PayscaleCalc.Payscale.PayScaleQuoteResponse> PayScaleQuoteAsync(PayscaleCalc.Payscale.PayScaleQuoteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class SuggestJobsRequest : JobCompSearchRequest {
        
        private int maxResultsField;
        
        private bool maxResultsFieldSpecified;
        
        private Location locationField;
        
        private MatchType matchTypeField;
        
        private SuggestJobsFilterType filterTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MaxResults {
            get {
                return this.maxResultsField;
            }
            set {
                this.maxResultsField = value;
                this.RaisePropertyChanged("MaxResults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxResultsSpecified {
            get {
                return this.maxResultsFieldSpecified;
            }
            set {
                this.maxResultsFieldSpecified = value;
                this.RaisePropertyChanged("MaxResultsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MatchType MatchType {
            get {
                return this.matchTypeField;
            }
            set {
                this.matchTypeField = value;
                this.RaisePropertyChanged("MatchType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SuggestJobsFilterType FilterType {
            get {
                return this.filterTypeField;
            }
            set {
                this.filterTypeField = value;
                this.RaisePropertyChanged("FilterType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class Location : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string stateField;
        
        private string cityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class CompensationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double averageField;
        
        private double medianField;
        
        private double percentile25Field;
        
        private double percentile75Field;
        
        private CompensationType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Average {
            get {
                return this.averageField;
            }
            set {
                this.averageField = value;
                this.RaisePropertyChanged("Average");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Median {
            get {
                return this.medianField;
            }
            set {
                this.medianField = value;
                this.RaisePropertyChanged("Median");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Percentile25 {
            get {
                return this.percentile25Field;
            }
            set {
                this.percentile25Field = value;
                this.RaisePropertyChanged("Percentile25");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Percentile75 {
            get {
                return this.percentile75Field;
            }
            set {
                this.percentile75Field = value;
                this.RaisePropertyChanged("Percentile75");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public CompensationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public enum CompensationType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Salary,
        
        /// <remarks/>
        Hourly,
        
        /// <remarks/>
        TotalAnnualCompensation,
        
        /// <remarks/>
        Monthly,
        
        /// <remarks/>
        AnnualizedBasePay,
        
        /// <remarks/>
        TotalCashCompensation,
        
        /// <remarks/>
        Bonus,
        
        /// <remarks/>
        Commission,
        
        /// <remarks/>
        ProfitShare,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PayScaleQuoteResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuggestJobsResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class CompensationSearchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CompensationSearchError errorField;
        
        private string callerCookieField;
        
        private string responseIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CompensationSearchError Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CallerCookie {
            get {
                return this.callerCookieField;
            }
            set {
                this.callerCookieField = value;
                this.RaisePropertyChanged("CallerCookie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResponseID {
            get {
                return this.responseIDField;
            }
            set {
                this.responseIDField = value;
                this.RaisePropertyChanged("ResponseID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public enum CompensationSearchError {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Unexpected,
        
        /// <remarks/>
        AccessDenied,
        
        /// <remarks/>
        JobNotFound,
        
        /// <remarks/>
        JobNotPreciseEnough,
        
        /// <remarks/>
        NotEnoughData,
        
        /// <remarks/>
        InvalidParameter,
        
        /// <remarks/>
        InvalidProfile,
        
        /// <remarks/>
        InvalidProfileID,
        
        /// <remarks/>
        InvalidJob,
        
        /// <remarks/>
        InvalidYearsOnJob,
        
        /// <remarks/>
        InvalidLocation,
        
        /// <remarks/>
        InvalidCountry,
        
        /// <remarks/>
        InvalidState,
        
        /// <remarks/>
        InvalidCity,
        
        /// <remarks/>
        InvalidCurrency,
        
        /// <remarks/>
        InvalidIncome,
        
        /// <remarks/>
        InvalidBaseIncome,
        
        /// <remarks/>
        InvalidOvertime,
        
        /// <remarks/>
        InvalidBonus,
        
        /// <remarks/>
        InvalidCommissions,
        
        /// <remarks/>
        InvalidExperience,
        
        /// <remarks/>
        InvalidDateOfBirth,
        
        /// <remarks/>
        InvalidNAICSCode,
        
        /// <remarks/>
        InvalidChartType,
        
        /// <remarks/>
        JobDescriptionNotFound,
        
        /// <remarks/>
        TemplateNotFound,
        
        /// <remarks/>
        NoMatchingSkills,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class PayScaleQuoteResponse : CompensationSearchResponse {
        
        private CompensationData[] payScaleQuotesField;
        
        private string chartURLField;
        
        private string locationTypeField;
        
        private string locationRegionField;
        
        private string locationMetroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PayScaleQuotes", Order=0)]
        public CompensationData[] PayScaleQuotes {
            get {
                return this.payScaleQuotesField;
            }
            set {
                this.payScaleQuotesField = value;
                this.RaisePropertyChanged("PayScaleQuotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChartURL {
            get {
                return this.chartURLField;
            }
            set {
                this.chartURLField = value;
                this.RaisePropertyChanged("ChartURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LocationType {
            get {
                return this.locationTypeField;
            }
            set {
                this.locationTypeField = value;
                this.RaisePropertyChanged("LocationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LocationRegion {
            get {
                return this.locationRegionField;
            }
            set {
                this.locationRegionField = value;
                this.RaisePropertyChanged("LocationRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LocationMetro {
            get {
                return this.locationMetroField;
            }
            set {
                this.locationMetroField = value;
                this.RaisePropertyChanged("LocationMetro");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class SuggestJobsResponse : CompensationSearchResponse {
        
        private string[] jobsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Jobs", Order=0)]
        public string[] Jobs {
            get {
                return this.jobsField;
            }
            set {
                this.jobsField = value;
                this.RaisePropertyChanged("Jobs");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class Income : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal baseField;
        
        private decimal overtimeField;
        
        private decimal bonusField;
        
        private decimal commissionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
                this.RaisePropertyChanged("Base");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Overtime {
            get {
                return this.overtimeField;
            }
            set {
                this.overtimeField = value;
                this.RaisePropertyChanged("Overtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Bonus {
            get {
                return this.bonusField;
            }
            set {
                this.bonusField = value;
                this.RaisePropertyChanged("Bonus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Commissions {
            get {
                return this.commissionsField;
            }
            set {
                this.commissionsField = value;
                this.RaisePropertyChanged("Commissions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class Degree : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schoolField;
        
        private string nameField;
        
        private string majorField;
        
        private int yearField;
        
        private bool yearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string School {
            get {
                return this.schoolField;
            }
            set {
                this.schoolField = value;
                this.RaisePropertyChanged("School");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
                this.RaisePropertyChanged("Major");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
                this.RaisePropertyChanged("YearSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class Education : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int yearsInSchoolField;
        
        private bool yearsInSchoolFieldSpecified;
        
        private Degree[] degreesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int YearsInSchool {
            get {
                return this.yearsInSchoolField;
            }
            set {
                this.yearsInSchoolField = value;
                this.RaisePropertyChanged("YearsInSchool");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearsInSchoolSpecified {
            get {
                return this.yearsInSchoolFieldSpecified;
            }
            set {
                this.yearsInSchoolFieldSpecified = value;
                this.RaisePropertyChanged("YearsInSchoolSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Degrees", Order=1)]
        public Degree[] Degrees {
            get {
                return this.degreesField;
            }
            set {
                this.degreesField = value;
                this.RaisePropertyChanged("Degrees");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class Employer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int sizeField;
        
        private bool sizeFieldSpecified;
        
        private double yearsWithEmployerField;
        
        private bool yearsWithEmployerFieldSpecified;
        
        private string employerTypeField;
        
        private decimal grossRevenuesField;
        
        private bool grossRevenuesFieldSpecified;
        
        private string sICCodeField;
        
        private string nAICSCodeField;
        
        private string productActivityField;
        
        private string[] productActivitiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("SizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double YearsWithEmployer {
            get {
                return this.yearsWithEmployerField;
            }
            set {
                this.yearsWithEmployerField = value;
                this.RaisePropertyChanged("YearsWithEmployer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearsWithEmployerSpecified {
            get {
                return this.yearsWithEmployerFieldSpecified;
            }
            set {
                this.yearsWithEmployerFieldSpecified = value;
                this.RaisePropertyChanged("YearsWithEmployerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmployerType {
            get {
                return this.employerTypeField;
            }
            set {
                this.employerTypeField = value;
                this.RaisePropertyChanged("EmployerType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal GrossRevenues {
            get {
                return this.grossRevenuesField;
            }
            set {
                this.grossRevenuesField = value;
                this.RaisePropertyChanged("GrossRevenues");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrossRevenuesSpecified {
            get {
                return this.grossRevenuesFieldSpecified;
            }
            set {
                this.grossRevenuesFieldSpecified = value;
                this.RaisePropertyChanged("GrossRevenuesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SICCode {
            get {
                return this.sICCodeField;
            }
            set {
                this.sICCodeField = value;
                this.RaisePropertyChanged("SICCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NAICSCode {
            get {
                return this.nAICSCodeField;
            }
            set {
                this.nAICSCodeField = value;
                this.RaisePropertyChanged("NAICSCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ProductActivity {
            get {
                return this.productActivityField;
            }
            set {
                this.productActivityField = value;
                this.RaisePropertyChanged("ProductActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public string[] ProductActivities {
            get {
                return this.productActivitiesField;
            }
            set {
                this.productActivitiesField = value;
                this.RaisePropertyChanged("ProductActivities");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class PersonalInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateOfBirthField;
        
        private bool dateOfBirthFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("DateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfBirthSpecified {
            get {
                return this.dateOfBirthFieldSpecified;
            }
            set {
                this.dateOfBirthFieldSpecified = value;
                this.RaisePropertyChanged("DateOfBirthSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class Job : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private double yearsOnJobField;
        
        private bool yearsOnJobFieldSpecified;
        
        private double yearsExperienceField;
        
        private bool yearsExperienceFieldSpecified;
        
        private string[] jobsToUseField;
        
        private YearsExperienceRange yearsExperienceRangeField;
        
        private bool yearsExperienceRangeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double YearsOnJob {
            get {
                return this.yearsOnJobField;
            }
            set {
                this.yearsOnJobField = value;
                this.RaisePropertyChanged("YearsOnJob");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearsOnJobSpecified {
            get {
                return this.yearsOnJobFieldSpecified;
            }
            set {
                this.yearsOnJobFieldSpecified = value;
                this.RaisePropertyChanged("YearsOnJobSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double YearsExperience {
            get {
                return this.yearsExperienceField;
            }
            set {
                this.yearsExperienceField = value;
                this.RaisePropertyChanged("YearsExperience");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearsExperienceSpecified {
            get {
                return this.yearsExperienceFieldSpecified;
            }
            set {
                this.yearsExperienceFieldSpecified = value;
                this.RaisePropertyChanged("YearsExperienceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] JobsToUse {
            get {
                return this.jobsToUseField;
            }
            set {
                this.jobsToUseField = value;
                this.RaisePropertyChanged("JobsToUse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public YearsExperienceRange YearsExperienceRange {
            get {
                return this.yearsExperienceRangeField;
            }
            set {
                this.yearsExperienceRangeField = value;
                this.RaisePropertyChanged("YearsExperienceRange");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YearsExperienceRangeSpecified {
            get {
                return this.yearsExperienceRangeFieldSpecified;
            }
            set {
                this.yearsExperienceRangeFieldSpecified = value;
                this.RaisePropertyChanged("YearsExperienceRangeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public enum YearsExperienceRange {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        LessThanOne,
        
        /// <remarks/>
        OneToFour,
        
        /// <remarks/>
        FiveToNine,
        
        /// <remarks/>
        TenToNineteen,
        
        /// <remarks/>
        TwentyOrMore,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class UserProfile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string currencyNameField;
        
        private Job jobField;
        
        private Location locationField;
        
        private PersonalInfo personalField;
        
        private Employer employerField;
        
        private Education educationField;
        
        private Income incomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CurrencyName {
            get {
                return this.currencyNameField;
            }
            set {
                this.currencyNameField = value;
                this.RaisePropertyChanged("CurrencyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Job Job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
                this.RaisePropertyChanged("Job");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PersonalInfo Personal {
            get {
                return this.personalField;
            }
            set {
                this.personalField = value;
                this.RaisePropertyChanged("Personal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Employer Employer {
            get {
                return this.employerField;
            }
            set {
                this.employerField = value;
                this.RaisePropertyChanged("Employer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Education Education {
            get {
                return this.educationField;
            }
            set {
                this.educationField = value;
                this.RaisePropertyChanged("Education");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Income Income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
                this.RaisePropertyChanged("Income");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class PayscaleCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PayScaleQuoteRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JobCompSearchRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuggestJobsRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class CompensationSearchRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PayscaleCredentials credentialsField;
        
        private bool isTestField;
        
        private string callerCookieField;
        
        private string relatedResponseIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PayscaleCredentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
                this.RaisePropertyChanged("Credentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsTest {
            get {
                return this.isTestField;
            }
            set {
                this.isTestField = value;
                this.RaisePropertyChanged("IsTest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CallerCookie {
            get {
                return this.callerCookieField;
            }
            set {
                this.callerCookieField = value;
                this.RaisePropertyChanged("CallerCookie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RelatedResponseID {
            get {
                return this.relatedResponseIDField;
            }
            set {
                this.relatedResponseIDField = value;
                this.RaisePropertyChanged("RelatedResponseID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class PayScaleQuoteRequest : CompensationSearchRequest {
        
        private UserProfile profileField;
        
        private string userEnteredJobTitleField;
        
        private string generateChartTypeField;
        
        private string compensationTypeFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UserProfile Profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
                this.RaisePropertyChanged("Profile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserEnteredJobTitle {
            get {
                return this.userEnteredJobTitleField;
            }
            set {
                this.userEnteredJobTitleField = value;
                this.RaisePropertyChanged("UserEnteredJobTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GenerateChartType {
            get {
                return this.generateChartTypeField;
            }
            set {
                this.generateChartTypeField = value;
                this.RaisePropertyChanged("GenerateChartType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CompensationTypeFilter {
            get {
                return this.compensationTypeFilterField;
            }
            set {
                this.compensationTypeFilterField = value;
                this.RaisePropertyChanged("CompensationTypeFilter");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuggestJobsRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public partial class JobCompSearchRequest : CompensationSearchRequest {
        
        private string jobField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Job {
            get {
                return this.jobField;
            }
            set {
                this.jobField = value;
                this.RaisePropertyChanged("Job");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public enum MatchType {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Broad,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.payscale.com/compensationSearch/060930")]
    public enum SuggestJobsFilterType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        RequireCountryMatch,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PayScaleQuoteServiceSoapChannel : PayscaleCalc.Payscale.PayScaleQuoteServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PayScaleQuoteServiceSoapClient : System.ServiceModel.ClientBase<PayscaleCalc.Payscale.PayScaleQuoteServiceSoap>, PayscaleCalc.Payscale.PayScaleQuoteServiceSoap {
        
        public PayScaleQuoteServiceSoapClient() {
        }
        
        public PayScaleQuoteServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PayScaleQuoteServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayScaleQuoteServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayScaleQuoteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PayscaleCalc.Payscale.SuggestJobsResponse SuggestJobs(PayscaleCalc.Payscale.SuggestJobsRequest request) {
            return base.Channel.SuggestJobs(request);
        }
        
        public System.Threading.Tasks.Task<PayscaleCalc.Payscale.SuggestJobsResponse> SuggestJobsAsync(PayscaleCalc.Payscale.SuggestJobsRequest request) {
            return base.Channel.SuggestJobsAsync(request);
        }
        
        public PayscaleCalc.Payscale.PayScaleQuoteResponse PayScaleQuote(PayscaleCalc.Payscale.PayScaleQuoteRequest request) {
            return base.Channel.PayScaleQuote(request);
        }
        
        public System.Threading.Tasks.Task<PayscaleCalc.Payscale.PayScaleQuoteResponse> PayScaleQuoteAsync(PayscaleCalc.Payscale.PayScaleQuoteRequest request) {
            return base.Channel.PayScaleQuoteAsync(request);
        }
    }
}
